### ISSUE TITLE
Update information after video recording without clicking check mark

### ISSUE THREAD

**Issue by gleitz** [OpenWatch/OpenWatch-Android#3]
After you've recorded a video, you are taken to a screen that says "What Happened?"

I often enter tags on this page and then click the back button to go to the previous screen. I recently realized that I need to click the check mark in the upper right for these tags to be applied. Tags should be applied while typing, or you should have a screen that says "are you sure you want to go back without saving tags?"

**Comment by OnlyInAmerica** [comment]
Double checked, and tags are indeed saved even if you use the back button to navigate away from this Activity.

We'll overhaul this activity entirely in the next release.
